[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "hostelswap"
version = "0.0.1"
authors = [
  { name="Raghav B. Venkataramaiyer", email="bv.raghav@thapar.edu" },
]
description = "Multi-party hostel room swap-chain matching service"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    # See: https://pypi.org/classifiers/
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
]
dependencies = [
    "numpy",
    "scipy",
    "fastapi",
    "uvicorn",
]

[project.optional-dependencies]
dev = ["pytest", "httpx2"]

[project.urls]
Homepage = "https://github.com/AabhasK/ucs503p-202627-hostel-swapping-service"
Issues = "https://github.com/AabhasK/ucs503p-202627-hostel-swapping-service/issues"

[tool.hatch.build.targets.wheel]
packages = ["code/hostelswap"]

# Adapted from https://stackoverflow.com/a/50156706
[tool.pytest.ini_options]
pythonpath = ["code"]
testpaths = ["tests"]
